/**
 * Helm values types for the Solace PubSub+ Software Event Broker charts.
 *
 * Chart repo: https://solaceproducts.github.io/pubsubplus-kubernetes-helm-quickstart/helm-charts/
 * Charts (all share the same values schema):
 *   - pubsubplus      — single-node non-HA, prod1k, 30Gi storage
 *   - pubsubplus-dev  — minimum footprint single-node for development, dev, 10Gi storage
 *   - pubsubplus-ha   — HA redundancy group (Primary/Backup/Monitor), prod1k, 30Gi storage
 *
 * Generated from `helm show values solacecharts/pubsubplus` (v3.10.0).
 * Every top-level key and its nested structure is represented. All fields are
 * optional because the chart supplies defaults.
 */

import type { DeepPartial, ResourceRequirements } from '@cdk8s-charts/utils';

// ---------------------------------------------------------------------------
// solace.* — broker topology, scaling, credentials, scheduling
// ---------------------------------------------------------------------------

/** Fine-grained scaling tier; overrides `solace.size` when provided. */
export interface SolaceSystemScaling {
  /** Max supported client connections. */
  maxConnections: number;
  /** Max queue messages, in millions of messages. */
  maxQueueMessages: number;
  /** Max spool usage, in MB. Ensure `storage.size` is adequate. */
  maxSpoolUsage: number;
  /** CPUs in cores. */
  cpu: string;
  /** Host virtual memory (e.g. "3410Mi"). */
  memory: string;
  /** Maximum number of Kafka bridges. */
  maxKafkaBridgeCount?: number;
  /** Maximum number of connections to Kafka brokers. */
  maxKafkaBrokerConnectionCount?: number;
  /** Maximum number of bridges. */
  maxBridgeCount?: number;
  /** Maximum number of subscriptions. */
  maxSubscriptionCount?: number;
  /** Maximum guaranteed message size in MB. */
  maxGuaranteedMessageSize?: number;
}

/** Extra env var injected into the broker container. */
export interface SolaceExtraEnvVar {
  name: string;
  value: string;
}

export interface SolaceSolaceValues {
  /** `false` (default) single-node; `true` HA with Primary/Backup/Monitor. */
  redundancy?: boolean;
  /** Set up a PodDisruptionBudget for HA deployments (min 2 nodes). */
  podDisruptionBudgetForHA?: boolean;
  /** Scaling tier. Ignored when `systemScaling` is set. */
  size?: 'dev' | 'prod1k' | 'prod10k' | 'prod100k';
  /** Fine-grained scaling; overrides `size` when provided (all sub-settings required). */
  systemScaling?: SolaceSystemScaling;
  /** Enable the solace-pod-modifier admission plugin for Monitor node resources. */
  podModifierEnabled?: boolean;
  /** Plain-text admin password (autogenerated if empty; not recommended for production). */
  usernameAdminPassword?: string;
  /** Existing Secret (key `username_admin_password`) holding the admin password. */
  usernameAdminPasswordSecretName?: string;
  /** tz database timezone name; default UTC. */
  timezone?: string;
  /** Extra env vars added to the broker container (e.g. configuration keys). */
  extraEnvVars?: SolaceExtraEnvVar[];
  /** Existing ConfigMap containing extra environment variables. */
  extraEnvVarsCM?: string;
  /** Existing Secret containing extra environment variables (sensitive data). */
  extraEnvVarsSecret?: string;
  /** Affinity rules for the broker StatefulSet pod. */
  affinity?: Record<string, unknown>;
  /** Tolerations for the broker StatefulSet pods. */
  tolerations?: Array<Record<string, unknown>>;
}

// ---------------------------------------------------------------------------
// image.*
// ---------------------------------------------------------------------------

export interface SolaceImageValues {
  /** Image repo name and path to the Solace Event Broker container image. */
  repository?: string;
  /** Image tag. Pin an explicit tag for production. */
  tag?: string;
  /** Image pull policy. */
  pullPolicy?: 'Always' | 'IfNotPresent' | 'Never';
  /** Existing ImagePullSecret name for secure image repos. */
  pullSecretName?: string;
}

// ---------------------------------------------------------------------------
// securityContext.*
// ---------------------------------------------------------------------------

export interface SolaceSecurityContextValues {
  /** Enable pod security context (fsGroup + runAsUser). */
  enabled?: boolean;
  /** Pod fsGroup. */
  fsGroup?: number;
  /** Pod runAsUser. */
  runAsUser?: number;
}

// ---------------------------------------------------------------------------
// serviceAccount.*
// ---------------------------------------------------------------------------

export interface SolaceServiceAccountValues {
  /** Create a dedicated service account for the deployment. */
  create?: boolean;
  /** Service account name (must exist if `create=false`). */
  name?: string;
}

// ---------------------------------------------------------------------------
// tls.*
// ---------------------------------------------------------------------------

export interface SolaceTlsValues {
  /** Enable TLS for exposed broker services. */
  enabled?: boolean;
  /** Secret containing the server certificates (required when enabled). */
  serverCertificatesSecret?: string;
  /** Certificate filename inside the secret. */
  certFilename?: string;
  /** Certificate key filename inside the secret. */
  certKeyFilename?: string;
}

// ---------------------------------------------------------------------------
// service.*
// ---------------------------------------------------------------------------

export interface SolaceServicePort {
  /** External service port. */
  servicePort: number;
  /** Container port mapped to the service port. */
  containerPort: number;
  /** Protocol (typically TCP). */
  protocol?: string;
  /** Port name. */
  name: string;
}

export interface SolaceServiceValues {
  /** Service exposure type. */
  type?: 'ClusterIP' | 'NodePort' | 'LoadBalancer';
  /** Provider-specific service annotations. */
  annotations?: Record<string, string>;
  /** Service ports exposed for the broker. */
  ports?: SolaceServicePort[];
}

// ---------------------------------------------------------------------------
// storage.*
// ---------------------------------------------------------------------------

export interface SolaceStorageValues {
  /** `true` (default) for persistent storage; `false` for ephemeral (not recommended). */
  persistent?: boolean;
  /** `true` to indicate slow storage (e.g. NFS). */
  slow?: boolean;
  /** YAML fragment describing how to mount the data volume (overrides other storage params). */
  customVolumeMount?: string;
  /** StorageClass name; defaults to the cluster default. */
  useStorageClass?: string;
  /** Persistent storage size (refer to Solace docs for minimums). */
  size?: string;
  /** Storage size assigned to Monitor pods (initial deployments only). */
  monitorStorageSize?: string;
  /** Use a single mount point storage-group (recommended from broker v9.12). */
  useStorageGroup?: boolean;
}

// ---------------------------------------------------------------------------
// insights.* — Solace Insights agent + OTel forwarding
// ---------------------------------------------------------------------------

export interface SolaceInsightsEnvVars {
  /** API key for the Solace Insights subscription. */
  INSIGHTS_AGENT_API_KEY?: string;
  /** Site location where metrics/logs flow. */
  INSIGHTS_AGENT_SITE?: string;
  /** Tags for metrics and logs. */
  INSIGHTS_AGENT_TAGS?: string;
  /** Additional agent settings passed through verbatim. */
  [key: string]: string | undefined;
}

export interface SolaceInsightsImageValues {
  /** Insights Agent image repository. */
  repository?: string;
  /** Insights Agent image tag. */
  tag?: string;
  /** Image pull secret name for the Insights Agent. */
  pullSecretName?: string;
  /** Image pull policy for the Insights Agent. */
  pullPolicy?: 'Always' | 'IfNotPresent' | 'Never';
}

export interface SolaceInsightsForwardingValues {
  /** Master switch for Insights Agent Pro / OTel forwarding mode. */
  enabled?: boolean;
  /** Inline OTel collector config (otel-config.yaml). */
  otelConfig?: string;
  /** Per-node OTel config for the primary broker (HA pod-0). */
  otelConfigPrimary?: string;
  /** Per-node OTel config for the backup broker (HA pod-1). */
  otelConfigBackup?: string;
  /** Per-node OTel config for the monitor broker (HA pod-2). */
  otelConfigMonitor?: string;
  /** Inline override of the Datadog agent Solace log-collection config. */
  logsConfig?: string;
}

export interface SolaceInsightsValues {
  /** Enable collection of metrics and logs for the Solace broker. */
  enabled?: boolean;
  /** Environment variables for the Insights Agent. */
  environmentVariables?: SolaceInsightsEnvVars;
  /** Insights Agent container image. */
  image?: SolaceInsightsImageValues;
  /** Insights Agent container resources. */
  resources?: ResourceRequirements;
  /** Insights Agent Pro / third-party forwarding configuration. */
  forwarding?: SolaceInsightsForwardingValues;
}

// ---------------------------------------------------------------------------
// Top-level chart values (shared by all three Solace charts)
// ---------------------------------------------------------------------------

export interface SolaceValues {
  /** Override `<release-name>-<chart-name>` naming. */
  nameOverride?: string;
  /** Fully override Kubernetes object names. */
  fullnameOverride?: string;
  /** Broker topology, scaling, credentials, and scheduling. */
  solace?: SolaceSolaceValues;
  /** Solace Event Broker container image. */
  image?: SolaceImageValues;
  /** Pod security context. */
  securityContext?: SolaceSecurityContextValues;
  /** Inject service information into pod env vars (Docker links syntax). */
  enableServiceLinks?: boolean;
  /** Service account for the deployment. */
  serviceAccount?: SolaceServiceAccountValues;
  /** TLS configuration for exposed broker services. */
  tls?: SolaceTlsValues;
  /** Service exposure and ports. */
  service?: SolaceServiceValues;
  /** Storage configuration. */
  storage?: SolaceStorageValues;
  /** Solace Insights agent configuration. */
  insights?: SolaceInsightsValues;
}

// ---------------------------------------------------------------------------
// Construct props — convenience knobs mapped into Helm values (shared)
// ---------------------------------------------------------------------------

/** Convenience TLS props; mapped into `tls.*`. */
export interface SolaceTlsProps {
  /** Enable TLS for exposed broker services. */
  enabled?: boolean;
  /** Secret containing the server certificates (required when enabled). */
  serverCertificatesSecret?: string;
  /** Certificate filename inside the secret. */
  certFilename?: string;
  /** Certificate key filename inside the secret. */
  certKeyFilename?: string;
}

/** Convenience storage props; mapped into `storage.*`. */
export interface SolaceStorageProps {
  /** Use persistent storage (default `true`). */
  persistent?: boolean;
  /** Persistent storage size (chart default: `30Gi`, dev chart: `10Gi`). */
  size?: string;
  /** StorageClass name. */
  useStorageClass?: string;
  /** Indicate slow storage (e.g. NFS). */
  slow?: boolean;
  /** Use a single mount point storage-group (recommended from broker v9.12). */
  useStorageGroup?: boolean;
  /** Storage size for Monitor pods. */
  monitorStorageSize?: string;
  /** YAML fragment describing how to mount the data volume. */
  customVolumeMount?: string;
}

/** Convenience Insights props; mapped into `insights.*`. */
export interface SolaceInsightsProps {
  /** Enable collection of metrics and logs for the Solace broker. */
  enabled?: boolean;
  /** API key for the Solace Insights subscription. */
  apiKey?: string;
  /** Site location where metrics/logs flow. */
  site?: string;
  /** Tags for metrics and logs. */
  tags?: string;
  /** Insights Agent container image. */
  image?: SolaceInsightsImageValues;
  /** Insights Agent container resources. */
  resources?: ResourceRequirements;
  /** Insights Agent Pro / third-party forwarding configuration. */
  forwarding?: SolaceInsightsForwardingValues;
  /** Additional environment variables passed through verbatim. */
  extraEnvironmentVariables?: Record<string, string>;
}

export interface SolaceProps {
  namespace: string;
  /** `true` for HA (Primary/Backup/Monitor); default `false` (single-node). HA chart defaults to `true`. */
  redundancy?: boolean;
  /** Scaling tier by max connections. Ignored when `systemScaling` is set. Defaults: `prod1k` (standard/HA), `dev` (dev chart). */
  size?: 'dev' | 'prod1k' | 'prod10k' | 'prod100k';
  /** Fine-grained scaling; overrides `size` when provided. */
  systemScaling?: SolaceSystemScaling;
  /** Plain-text admin password (autogenerated if omitted; not recommended for production). */
  adminPassword?: string;
  /** Existing Secret (key `username_admin_password`) holding the admin password. */
  adminPasswordSecretName?: string;
  /** tz database timezone name; default UTC. */
  timezone?: string;
  /** Convenience TLS toggle. */
  tls?: SolaceTlsProps;
  /** Service exposure type; default `LoadBalancer`. */
  serviceType?: 'ClusterIP' | 'NodePort' | 'LoadBalancer';
  /** Convenience storage knobs. */
  storage?: SolaceStorageProps;
  /** Solace Insights agent configuration. */
  insights?: SolaceInsightsProps;
  /** Helm chart name/ref; defaults to the chart this construct wraps. */
  chart?: string;
  /** Helm repository URL; defaults to the upstream Solace charts repo. */
  repo?: string;
  /** Optional Helm chart version pin; defaults to `3.10.0`. */
  version?: string;
  /** Raw Helm value overrides (deep-merged into computed values). */
  values?: DeepPartial<SolaceValues>;
}

// ---------------------------------------------------------------------------
// Construct exports — for cross-service wiring (shared)
// ---------------------------------------------------------------------------

export interface SolaceExports {
  /** Service DNS name (e.g. "pubsubplus"). */
  host: string;
  /** Solace SMF port (default 55555). */
  smfPort: number;
  /** SEMP management API port (default 8080). */
  sempPort: number;
  /** AMQP port (default 5672). */
  amqpPort: number;
  /** MQTT port (default 1883). */
  mqttPort: number;
  /** REST port (default 9000). */
  restPort: number;
  /** Resolved service type. */
  serviceType: string;
}
